More v2 tweaks
appdevdesigns/appbuilder_platform_mobile pull request #6
Opened 2023-05-08 07:03 UTC by Achoobert

The datadollection.QL() never gets any data. As far as I can tell, it is a webix datacollection function, and much of that was removed from `platform`

2023-05-08 18:03 UTC, Hiro-Nakamura requested changes
Just a couple of things to look at.

2023-05-08 18:03 UTC, Hiro-Nakamura commented on AppBuilder/platform/ABDataCollection.js
> +            if (data === "[Object, object]" || data === "[object Object]") {
I wonder if you could do `if (data.toLowerCase?.() === "[object, object]")`  to catch any/all permutations of the `object, object` reference.

2023-05-08 18:03 UTC, Hiro-Nakamura commented on AppBuilder/platform/ABDataCollection.js
> +      debugger;
`// debugger;`

2023-05-08 18:03 UTC, Hiro-Nakamura commented on AppBuilder/platform/ABDataCollection.js
> +      if (dc) {
not sure if you have additional plans for this, but 
-  you have already done a `return this.data;` above and will never get here
- the name of the method is `getAllRecords()` and this only looks like you are returning 1

2023-05-08 18:03 UTC, Hiro-Nakamura commented on AppBuilder/platform/ABDataCollection.js
> +      debugger;
again, assuming you are sill in process with this PR, but don't leave `debugger;` statements in live code.

2023-05-08 18:03 UTC, Hiro-Nakamura commented on AppBuilder/platform/ABObject.js
> +   urlRestRefresh() {
this one is left over from a long time ago, and I don't think it is a current `api` anymore.  You'll need to see where this is being called and make sure we rethink what that code was doing.

2023-05-08 18:03 UTC, Hiro-Nakamura commented on AppBuilder/platform/ABObject.js
> +      return `/app_builder/model/count/${this.id}`;
this one is now: `/app_builder/model${this.id}/count`

2023-05-08 18:03 UTC, Hiro-Nakamura requested changes
Just a couple of things to look at.

2023-05-15 03:24 UTC, Achoobert commented on AppBuilder/platform/ABDataCollection.js
> +            if (data === "[Object, object]" || data === "[object Object]") {
This is an error that should **only** be thrown in **development** when somone changes definitions, I saw it when a data collection was misconfigured. 
However, it was _really_ annoying to get invalid data that looked valid in the console: **should this code stay in produciton code?**

2023-06-12 14:14 UTC, Achoobert commented on AppBuilder/platform/ABDataCollection.js
> +      if (dc) {
this.data is an array, it should just be dumping the whole thing back

2023-06-12 14:15 UTC, Achoobert commented on AppBuilder/platform/ABObject.js
> +   urlRestRefresh() {
Added notify.developer

2023-06-12 15:05 UTC, merged